language: python
python:
  - "3.7-dev" # 3.7 development branch
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script: python -m unittest discover -v tests
#after_success:
#  - coverage run -m unittest discover
#  - codecov
