language: python
python:
  - "3.7-dev" # 3.7 development branch
# command to install dependencies
install: "pip install -r test-requirements.txt"
# command to run tests
script: python -m unittest discover -v tests
#after_success:
#  - coverage run -m unittest discover
#  - codecov
